string = 'TCTGACACAACATTTTGAACATTTTGAAGCATCTGAAGCATCTGTCTGACACAACATTTTGAACATTTTGTTGTCCCTGTCTGACACCGCACAGACCGCACAGACAACATTTTGAACATTTTGCGCACAGACTCTGACACAAGCATCTGCGCACAGACAACATTTTGTCTGACACTCTGACACCGCACAGACAACATTTTGTCTGACACCGCACAGACAACATTTTGTCTGACACTTGTCCCTGTCTGACACCGCACAGACTTGTCCCTGTCTGACACTCTGACACAACATTTTGTCTGACACCGCACAGACTTGTCCCTGAAGCATCTGCGCACAGACCGCACAGACAACATTTTGCGCACAGACAACATTTTGTCTGACACTTGTCCCTGAACATTTTGTCTGACACAAGCATCTGTTGTCCCTGTTGTCCCTGTTGTCCCTGCGCACAGACTCTGACACCGCACAGACAAGCATCTGTTGTCCCTGTTGTCCCTGTTGTCCCTGTTGTCCCTGTCTGACACCGCACAGACTTGTCCCTGTCTGACACTTGTCCCTGAACATTTTGCGCACAGACTCTGACACTCTGACACTCTGACACTTGTCCCTGAAGCATCTGAAGCATCTGAAGCATCTGTCTGACACTTGTCCCTGCGCACAGACCGCACAGACCGCACAGACTTGTCCCTGTCTGACACAACATTTTGAAGCATCTGTTGTCCCTGAAGCATCTGCGCACAGACAACATTTTGAAGCATCTGAAGCATCTGTCTGACACCGCACAGACAACATTTTGAAGCATCTGAACATTTTG'
k = int(14)

#Generate hastable
kmer_count = {}
for n in range(len(string) - k):
  c = string[n:n+k]
  kmer_count[c] = kmer_count[c] + 1 if c in kmer_count else 1

max = 0
max_kmer = []
for k,v in kmer_count.items():
  if v > max:
    max_kmer = [k]
    max = v
  elif v == max:
    max_kmer += [k]

print (max_kmer)
